### PR TITLE
Add ember observer client application into apps/

### PR DESCRIPTION
**Pull request by SYU15**
This is the second test application we will use to validate `$edb` against.

### CODE REVIEW

**Comment by SYU15** [comment]
Yeah just gonna keep pushing until this no longer breaks :) Please ignore.

**Comment by SYU15** [comment]
I am not sure if I should `apps/ember-observer/package-lock.json` and have the git workflow use `npm` but the README said to use `npm install`. `yarn install` caused missing dependency errors (even though there is a `yarn.lock` file?). Confused a bit. Anyone know which direction I should take?

**Comment by chancancode** [comment]
> I am not sure if I should have checked in apps/ember-observer/package-lock.json and have the git workflow use npm but the README said to use npm install. yarn install caused missing dependency errors (even though there is a yarn.lock file?). Confused a bit. Anyone know which direction I should take?

The readme is just wrong; it's supposed to be `yarn install`.

**Comment by SYU15** [comment]
Tested locally and it works as expected.

Screen Shot 2020-08-26 at 12 26 01 PM

**Comment by chancancode** [comment]
Closed via #10

**Pull request closed without merging**
