### PR TITLE
Add ember-observer redux

### PR DESCRIPTION
**Pull request by chancancode**
Rebased version of #9, combined and reordered some of the commits to keep a cleaner history to hopefully make future conflict resolution easier

### CODE REVIEW

**Comment by chancancode** [comment]
@SYU15 we should probably upstream some of the changes to ember-observer: in particular, the commit that updates the ember-try config and adding the dependency to package.json probably makes sense. cc @kategengler

**Comment by SYU15** [comment]
@kategengler I can make the changes if that helps at all :)

**Comment by kategengler** [comment]
Happy to have the ember-try dep & config upstreamed.

**Comment by SYU15** [comment]
@kategengler @chancancode PR here: https://github.com/emberobserver/client/pull/204

**Pull request merged**
